### PR TITLE
Collection endpoint

### PR DESCRIPTION
**Pull request by jjfrench**
Porting over changes from https://github.com/NASA-IMPACT/veda-stac-ingestor/pull/29

### CODE REVIEW

**Comment by sharkinsspatial** [comment]
@jjfrench I'll try to review in detail tomorrow.  The first thing I noted is that we have no additional tests for the logic in this PR.  A bit deeper look revealed that our CI actions are not running internal lib tests at all.  @alukach Did you have a specific approach you'd like to see for running internal lib tests such as https://github.com/developmentseed/cdk-pgstac/blob/main/lib/ingestor-api/runtime/tests/test_registration.py for new PRs?  I've never built a generic construct like this so I'm unsure what the best practice should be.

**Comment by sharkinsspatial** [comment]
@jjfrench Here is the branch / PR with a test runner.  You should be able to merge this branch and then build tests for your collection endpoint.

**Comment by jjfrench** [comment]
> @jjfrench Here is the branch / PR with a test runner. You should be able to merge this branch and then build tests for your collection endpoint.

Hey @sharkinsspatial, did you mean to link https://github.com/developmentseed/cdk-pgstac/pull/10? Or was there another branch you were referencing?

**Comment by sharkinsspatial** [comment]
🤦 That's the one.

**Comment by sharkinsspatial** [comment]
@jjfrench I'm confused, it looks like that rather than fetching and merging my `ci_tests` branch that you copied code over and created your own commits 🤔.  Was there a reason for this.  At this point given the number of extra `chore` commits you made it might best to

**Pull request closed without merging**
